---
title: "Observable with reactable in Quarto"
format:
  html:
    echo: false
---

Source code: [observable-reactable.qmd](https://github.com/glin/reactable/blob/main/vignettes/quarto/observable-reactable.qmd)

## Observable Inputs to filter reactable

```{r}
#| include: false

data <- read.csv("palmer-penguins.csv")

ojs_define(data = data)

```
```{ojs}
//| panel: input
viewof billLengthMin = Inputs.range(
  [32, 50], 
  { value: 35, step: 1, label: "Bill length (min):" }
)

viewof islands = Inputs.checkbox(
  ["Torgersen", "Biscoe", "Dream"], 
  { value: ["Torgersen", "Biscoe"], label: "Islands:" }
)

filtered = transpose(data).filter(penguin => {
  return penguin.bill_length > billLengthMin && islands.includes(penguin.island)
})

```

```{ojs}
//| include: false

// Update table data when filtered data changes
Reactable.setData('tbl', filtered)

```

```{r}
#| warning: false

library(reactable)

reactable(
  data,
  wrap = FALSE,
  resizable = TRUE,
  minRows = 10,
  elementId = "tbl"
)
```


